import enum


class RoleName(str, enum.Enum):
    USER = "USER"
    DEPARTMENT_ADMIN = "DEPARTMENT_ADMIN"
    LEGAL_REVIEWER = "LEGAL_REVIEWER"
    EXECUTIVE = "EXECUTIVE"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    # 소송·분쟁 사건 메뉴 접근 권한 — 자가 회원가입 승인 시 관리자가 선택적으로 부여한다.
    LITIGATION_ACCESS = "LITIGATION_ACCESS"


class ApprovalStatus(str, enum.Enum):
    """Self-signup accounts move PENDING_EMAIL_VERIFICATION -> PENDING_ADMIN_APPROVAL
    -> APPROVED. Admin-created accounts (POST /api/users) start at APPROVED directly,
    skipping both gates, since an admin already vouched for them."""

    PENDING_EMAIL_VERIFICATION = "PENDING_EMAIL_VERIFICATION"
    PENDING_ADMIN_APPROVAL = "PENDING_ADMIN_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ContractType(str, enum.Enum):
    SUBCONTRACT = "SUBCONTRACT"
    DESIGN_SUPERVISION_CM = "DESIGN_SUPERVISION_CM"
    GENERAL_SERVICE = "GENERAL_SERVICE"
    PURCHASE_SUPPLY = "PURCHASE_SUPPLY"
    SOFTWARE_SAAS = "SOFTWARE_SAAS"
    NDA = "NDA"
    MOU = "MOU"
    CONSORTIUM = "CONSORTIUM"
    CONSULTING = "CONSULTING"
    LEASE = "LEASE"
    PERSONAL_DATA_PROCESSING = "PERSONAL_DATA_PROCESSING"
    OTHER = "OTHER"


CONTRACT_TYPE_LABELS_KO = {
    ContractType.SUBCONTRACT: "하도급계약",
    ContractType.DESIGN_SUPERVISION_CM: "설계·감리·CM 용역계약",
    ContractType.GENERAL_SERVICE: "일반 용역계약",
    ContractType.PURCHASE_SUPPLY: "물품구매·공급계약",
    ContractType.SOFTWARE_SAAS: "소프트웨어·SaaS 계약",
    ContractType.NDA: "비밀유지계약",
    ContractType.MOU: "업무협약·MOU",
    ContractType.CONSORTIUM: "공동수급·컨소시엄 협약",
    ContractType.CONSULTING: "자문·위임계약",
    ContractType.LEASE: "임대차계약",
    ContractType.PERSONAL_DATA_PROCESSING: "개인정보 처리위탁계약",
    ContractType.OTHER: "기타 계약",
}


class TopecPosition(str, enum.Enum):
    CLIENT = "CLIENT"
    PRINCIPAL_CONTRACTOR = "PRINCIPAL_CONTRACTOR"
    SUBCONTRACTOR = "SUBCONTRACTOR"
    SERVICE_PROVIDER = "SERVICE_PROVIDER"
    SERVICE_RECIPIENT = "SERVICE_RECIPIENT"
    SUPPLIER = "SUPPLIER"
    PURCHASER = "PURCHASER"
    CONFIDENTIAL_INFO_PROVIDER = "CONFIDENTIAL_INFO_PROVIDER"
    CONFIDENTIAL_INFO_RECIPIENT = "CONFIDENTIAL_INFO_RECIPIENT"
    CONSORTIUM_MEMBER = "CONSORTIUM_MEMBER"
    OTHER = "OTHER"


TOPEC_POSITION_LABELS_KO = {
    TopecPosition.CLIENT: "발주자",
    TopecPosition.PRINCIPAL_CONTRACTOR: "원사업자",
    TopecPosition.SUBCONTRACTOR: "수급사업자·하도급업체",
    TopecPosition.SERVICE_PROVIDER: "용역 제공자",
    TopecPosition.SERVICE_RECIPIENT: "용역 수령자",
    TopecPosition.SUPPLIER: "공급자",
    TopecPosition.PURCHASER: "구매자",
    TopecPosition.CONFIDENTIAL_INFO_PROVIDER: "비밀정보 제공자",
    TopecPosition.CONFIDENTIAL_INFO_RECIPIENT: "비밀정보 수령자",
    TopecPosition.CONSORTIUM_MEMBER: "공동수급체 구성원",
    TopecPosition.OTHER: "기타",
}


class DocumentCategory(str, enum.Enum):
    CONTRACT = "CONTRACT"
    LITIGATION = "LITIGATION"


DOCUMENT_CATEGORY_LABELS_KO = {
    DocumentCategory.CONTRACT: "계약서 검토",
    DocumentCategory.LITIGATION: "소송·분쟁 문서 검토",
}


class LitigationDocumentType(str, enum.Enum):
    COMPLAINT = "COMPLAINT"  # 소장
    ANSWER = "ANSWER"  # 답변서
    PREPARATORY_BRIEF = "PREPARATORY_BRIEF"  # 준비서면
    APPEAL_BRIEF = "APPEAL_BRIEF"  # 항소·상고 이유서
    RULING = "RULING"  # 결정문
    JUDGMENT = "JUDGMENT"  # 판결문
    DEMAND_LETTER = "DEMAND_LETTER"  # 내용증명·최고장
    OTHER = "OTHER"


LITIGATION_DOCUMENT_TYPE_LABELS_KO = {
    LitigationDocumentType.COMPLAINT: "소장",
    LitigationDocumentType.ANSWER: "답변서",
    LitigationDocumentType.PREPARATORY_BRIEF: "준비서면",
    LitigationDocumentType.APPEAL_BRIEF: "항소·상고 이유서",
    LitigationDocumentType.RULING: "결정문",
    LitigationDocumentType.JUDGMENT: "판결문",
    LitigationDocumentType.DEMAND_LETTER: "내용증명·최고장",
    LitigationDocumentType.OTHER: "기타",
}


class TopecLitigationPosition(str, enum.Enum):
    PLAINTIFF = "PLAINTIFF"  # 원고
    DEFENDANT = "DEFENDANT"  # 피고
    INTERVENOR = "INTERVENOR"  # 보조참가인
    OTHER = "OTHER"


TOPEC_LITIGATION_POSITION_LABELS_KO = {
    TopecLitigationPosition.PLAINTIFF: "원고",
    TopecLitigationPosition.DEFENDANT: "피고",
    TopecLitigationPosition.INTERVENOR: "보조참가인",
    TopecLitigationPosition.OTHER: "기타",
}


class SecurityLevel(str, enum.Enum):
    INTERNAL = "INTERNAL"
    IMPORTANT = "IMPORTANT"
    CONFIDENTIAL = "CONFIDENTIAL"


class RetentionPolicy(str, enum.Enum):
    DELETE_AFTER_ANALYSIS = "DELETE_AFTER_ANALYSIS"
    KEEP_30_DAYS = "KEEP_30_DAYS"
    KEEP_1_YEAR = "KEEP_1_YEAR"
    KEEP_UNTIL_MANUAL_DELETE = "KEEP_UNTIL_MANUAL_DELETE"


class DocumentStatus(str, enum.Enum):
    UPLOADED = "UPLOADED"
    VALIDATING = "VALIDATING"
    EXTRACTING = "EXTRACTING"
    OCR_PROCESSING = "OCR_PROCESSING"
    STRUCTURING = "STRUCTURING"
    ANALYZING = "ANALYZING"
    WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"
    REVIEW_IN_PROGRESS = "REVIEW_IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"
    DELETED = "DELETED"


class LegalReviewStatus(str, enum.Enum):
    NOT_REQUESTED = "NOT_REQUESTED"
    REQUESTED = "REQUESTED"
    ASSIGNED = "ASSIGNED"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    COMPLETED = "COMPLETED"


class ClauseType(str, enum.Enum):
    DEFINITIONS = "DEFINITIONS"
    PURPOSE = "PURPOSE"
    SCOPE = "SCOPE"
    DELIVERABLES = "DELIVERABLES"
    CONTRACT_AMOUNT = "CONTRACT_AMOUNT"
    PAYMENT = "PAYMENT"
    ADVANCE_PAYMENT = "ADVANCE_PAYMENT"
    PRICE_ADJUSTMENT = "PRICE_ADJUSTMENT"
    CHANGE_ORDER = "CHANGE_ORDER"
    ADDITIONAL_WORK = "ADDITIONAL_WORK"
    ACCEPTANCE = "ACCEPTANCE"
    SCHEDULE = "SCHEDULE"
    DELAY_PENALTY = "DELAY_PENALTY"
    WARRANTY = "WARRANTY"
    PERFORMANCE_BOND = "PERFORMANCE_BOND"
    DAMAGES = "DAMAGES"
    LIABILITY_LIMIT = "LIABILITY_LIMIT"
    INDEMNITY = "INDEMNITY"
    INSURANCE = "INSURANCE"
    INTELLECTUAL_PROPERTY = "INTELLECTUAL_PROPERTY"
    CONFIDENTIALITY = "CONFIDENTIALITY"
    PERSONAL_DATA = "PERSONAL_DATA"
    TECHNICAL_DATA = "TECHNICAL_DATA"
    SUBCONTRACTING = "SUBCONTRACTING"
    ASSIGNMENT = "ASSIGNMENT"
    TERMINATION = "TERMINATION"
    FORCE_MAJEURE = "FORCE_MAJEURE"
    DISPUTE_RESOLUTION = "DISPUTE_RESOLUTION"
    GOVERNING_LAW = "GOVERNING_LAW"
    JURISDICTION = "JURISDICTION"
    RENEWAL = "RENEWAL"
    NOTICES = "NOTICES"
    SURVIVAL = "SURVIVAL"
    COMPLIANCE = "COMPLIANCE"
    SAFETY = "SAFETY"
    OTHER = "OTHER"


class RiskLevel(str, enum.Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    ACCEPTABLE = "ACCEPTABLE"


RISK_LEVEL_LABELS_KO = {
    RiskLevel.CRITICAL: "매우 높음",
    RiskLevel.HIGH: "높음",
    RiskLevel.MEDIUM: "보통",
    RiskLevel.LOW: "낮음",
    RiskLevel.ACCEPTABLE: "적정",
}


class RevisionLevel(str, enum.Enum):
    MINIMUM = "MINIMUM"
    STANDARD = "STANDARD"
    STRONG = "STRONG"


REVISION_LEVEL_LABELS_KO = {
    RevisionLevel.MINIMUM: "최소 수정안",
    RevisionLevel.STANDARD: "권고 수정안",
    RevisionLevel.STRONG: "TOPEC 보호 강화안",
}


class SourceType(str, enum.Enum):
    RULE_ONLY = "RULE_ONLY"
    AI_ONLY = "AI_ONLY"
    RULE_AND_AI = "RULE_AND_AI"


class KnowledgeDocType(str, enum.Enum):
    STATUTE = "STATUTE"
    ENFORCEMENT_DECREE = "ENFORCEMENT_DECREE"
    ENFORCEMENT_RULE = "ENFORCEMENT_RULE"
    NOTIFICATION = "NOTIFICATION"
    ADMIN_GUIDELINE = "ADMIN_GUIDELINE"
    COURT_CASE = "COURT_CASE"
    STANDARD_CONTRACT = "STANDARD_CONTRACT"
    TOPEC_STANDARD_CLAUSE = "TOPEC_STANDARD_CLAUSE"
    PAST_REVIEW_OPINION = "PAST_REVIEW_OPINION"
    EXTERNAL_COUNSEL_OPINION = "EXTERNAL_COUNSEL_OPINION"
    DISPUTE_CASE = "DISPUTE_CASE"
    REVIEW_CHECKLIST = "REVIEW_CHECKLIST"


class AuditAction(str, enum.Enum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    LOGOUT = "LOGOUT"
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DISABLED = "USER_DISABLED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_VIEWED = "DOCUMENT_VIEWED"
    DOCUMENT_DOWNLOADED = "DOCUMENT_DOWNLOADED"
    DOCUMENT_ANALYSIS_STARTED = "DOCUMENT_ANALYSIS_STARTED"
    DOCUMENT_ANALYSIS_COMPLETED = "DOCUMENT_ANALYSIS_COMPLETED"
    DOCUMENT_ANALYSIS_FAILED = "DOCUMENT_ANALYSIS_FAILED"
    DOCUMENT_UPDATED = "DOCUMENT_UPDATED"
    DOCUMENT_DELETED = "DOCUMENT_DELETED"
    REPORT_CREATED = "REPORT_CREATED"
    REPORT_DOWNLOADED = "REPORT_DOWNLOADED"
    LEGAL_REVIEW_REQUESTED = "LEGAL_REVIEW_REQUESTED"
    LEGAL_REVIEW_ASSIGNED = "LEGAL_REVIEW_ASSIGNED"
    LEGAL_REVIEW_COMPLETED = "LEGAL_REVIEW_COMPLETED"
    KNOWLEDGE_UPLOADED = "KNOWLEDGE_UPLOADED"
    KNOWLEDGE_UPDATED = "KNOWLEDGE_UPDATED"
    ROLE_CHANGED = "ROLE_CHANGED"
    SYSTEM_SETTING_CHANGED = "SYSTEM_SETTING_CHANGED"
    SIGNUP_REQUESTED = "SIGNUP_REQUESTED"
    SIGNUP_EMAIL_VERIFIED = "SIGNUP_EMAIL_VERIFIED"
    SIGNUP_APPROVED = "SIGNUP_APPROVED"
    SIGNUP_REJECTED = "SIGNUP_REJECTED"

    # 소송·분쟁 사건(LegalCase) 관련 — §30
    LEGAL_CASE_CREATED = "LEGAL_CASE_CREATED"
    LEGAL_CASE_UPDATED = "LEGAL_CASE_UPDATED"
    LEGAL_CASE_DELETED = "LEGAL_CASE_DELETED"
    CASE_BATCH_CREATED = "CASE_BATCH_CREATED"
    CASE_BATCH_UPLOAD_COMPLETED = "CASE_BATCH_UPLOAD_COMPLETED"
    CASE_BATCH_PARTIALLY_COMPLETED = "CASE_BATCH_PARTIALLY_COMPLETED"
    CASE_DOCUMENT_UPLOADED = "CASE_DOCUMENT_UPLOADED"
    CASE_DOCUMENT_DUPLICATE_DETECTED = "CASE_DOCUMENT_DUPLICATE_DETECTED"
    CASE_DOCUMENT_REANALYZED = "CASE_DOCUMENT_REANALYZED"
    CASE_ANALYSIS_STARTED = "CASE_ANALYSIS_STARTED"
    CASE_ANALYSIS_COMPLETED = "CASE_ANALYSIS_COMPLETED"
    CASE_ANALYSIS_FAILED = "CASE_ANALYSIS_FAILED"
    CASE_CHAT_QUESTIONED = "CASE_CHAT_QUESTIONED"
    CASE_FINAL_DOCUMENT_CREATED = "CASE_FINAL_DOCUMENT_CREATED"
    CASE_DOCUMENT_DOWNLOADED = "CASE_DOCUMENT_DOWNLOADED"


class LegalCaseStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"


LEGAL_CASE_STATUS_LABELS_KO = {
    LegalCaseStatus.ACTIVE: "진행 중",
    LegalCaseStatus.CLOSED: "종결",
}


class CaseUploadBatchStatus(str, enum.Enum):
    CREATED = "CREATED"
    PROCESSING = "PROCESSING"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


CASE_UPLOAD_BATCH_STATUS_LABELS_KO = {
    CaseUploadBatchStatus.CREATED: "대기",
    CaseUploadBatchStatus.PROCESSING: "처리 중",
    CaseUploadBatchStatus.PARTIALLY_COMPLETED: "일부 완료",
    CaseUploadBatchStatus.COMPLETED: "완료",
    CaseUploadBatchStatus.FAILED: "실패",
}


class CaseReportType(str, enum.Enum):
    PREPARATORY_BRIEF_DRAFT = "PREPARATORY_BRIEF_DRAFT"
    EXECUTIVE_SUMMARY = "EXECUTIVE_SUMMARY"


CASE_REPORT_TYPE_LABELS_KO = {
    CaseReportType.PREPARATORY_BRIEF_DRAFT: "준비서면 초안",
    CaseReportType.EXECUTIVE_SUMMARY: "경영진 보고 요약",
}
