"""add litigation document support

Revision ID: c60d861036a6
Revises: 73fa9dfb7c05
Create Date: 2026-07-23 17:35:02.600302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c60d861036a6'
down_revision: Union[str, None] = '73fa9dfb7c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'documents',
        sa.Column('document_category', sa.String(length=20), nullable=False, server_default='CONTRACT'),
    )
    op.add_column('documents', sa.Column('litigation_document_type', sa.String(length=30), nullable=True))
    op.add_column('documents', sa.Column('topec_litigation_position', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('case_number', sa.String(length=120), nullable=True))
    op.add_column('documents', sa.Column('court', sa.String(length=120), nullable=True))
    op.alter_column('documents', 'contract_type',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('documents', 'topec_position',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'topec_position',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('documents', 'contract_type',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.drop_column('documents', 'court')
    op.drop_column('documents', 'case_number')
    op.drop_column('documents', 'topec_litigation_position')
    op.drop_column('documents', 'litigation_document_type')
    op.drop_column('documents', 'document_category')
    # ### end Alembic commands ###
