"""add ai_cross_reviews table

Revision ID: ea6fa65776a4
Revises: f31882c69e58
Create Date: 2026-07-24 16:47:21.357330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea6fa65776a4'
down_revision: Union[str, None] = 'f31882c69e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cross_reviews',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('agreement_level', sa.String(length=20), nullable=False),
    sa.Column('overall_opinion', sa.Text(), nullable=False),
    sa.Column('additional_risks', sa.Text(), nullable=True),
    sa.Column('missed_points', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_cross_reviews')
    # ### end Alembic commands ###
