"""add case document extraction, relations, conflicts

Revision ID: f31882c69e58
Revises: e5c47cbc0a91
Create Date: 2026-07-24 11:00:53.545280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f31882c69e58'
down_revision: Union[str, None] = 'e5c47cbc0a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_conflicts',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('conflict_type', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('value_a', sa.Text(), nullable=False),
    sa.Column('source_document_a_id', sa.UUID(), nullable=True),
    sa.Column('value_b', sa.Text(), nullable=False),
    sa.Column('source_document_b_id', sa.UUID(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('recommended_check', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('resolution_status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['legal_cases.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_document_a_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_document_b_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_document_relations',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_a_id', sa.UUID(), nullable=False),
    sa.Column('document_b_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['legal_cases.id'], ),
    sa.ForeignKeyConstraint(['document_a_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['document_b_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_document_dates',
    sa.Column('case_document_id', sa.UUID(), nullable=False),
    sa.Column('date_type', sa.String(length=30), nullable=False),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_document_id'], ['case_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('case_documents', sa.Column('ai_suggested_document_type', sa.String(length=30), nullable=True))
    op.add_column('case_documents', sa.Column('classification_confidence', sa.Integer(), nullable=True))
    op.add_column('case_documents', sa.Column('classification_reasoning', sa.Text(), nullable=True))
    op.add_column('case_documents', sa.Column('extracted_case_number', sa.String(length=120), nullable=True))
    op.add_column('case_documents', sa.Column('extracted_court', sa.String(length=120), nullable=True))
    op.add_column('case_documents', sa.Column('extracted_plaintiff', sa.String(length=255), nullable=True))
    op.add_column('case_documents', sa.Column('extracted_defendant', sa.String(length=255), nullable=True))
    op.add_column('case_documents', sa.Column('extracted_plaintiff_counsel', sa.String(length=255), nullable=True))
    op.add_column('case_documents', sa.Column('extracted_defendant_counsel', sa.String(length=255), nullable=True))
    op.add_column('case_documents', sa.Column('case_info_confidence', sa.Integer(), nullable=True))
    op.add_column(
        'case_documents',
        sa.Column('needs_user_confirmation', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_documents', 'needs_user_confirmation')
    op.drop_column('case_documents', 'case_info_confidence')
    op.drop_column('case_documents', 'extracted_defendant_counsel')
    op.drop_column('case_documents', 'extracted_plaintiff_counsel')
    op.drop_column('case_documents', 'extracted_defendant')
    op.drop_column('case_documents', 'extracted_plaintiff')
    op.drop_column('case_documents', 'extracted_court')
    op.drop_column('case_documents', 'extracted_case_number')
    op.drop_column('case_documents', 'classification_reasoning')
    op.drop_column('case_documents', 'classification_confidence')
    op.drop_column('case_documents', 'ai_suggested_document_type')
    op.drop_table('case_document_dates')
    op.drop_table('case_document_relations')
    op.drop_table('case_conflicts')
    # ### end Alembic commands ###
